version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecom
    ports: ["3306:3306"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword"]
      interval: 5s
      timeout: 3s
      retries: 20
  app:
    build: .
    environment:
      DB_HOST: db
      DB_NAME: ecom
      DB_USER: root
      DB_PASSWORD: password
    ports: ["8080:8080"]
    depends_on:
      db:
        condition: service_healthy
